name: GitLab Test template
on:
  push:
    branches: gh-pages
  pull_request:
jobs:
  check-template:
    name: ${{ matrix.lesson-name }} (${{ matrix.os-name }})
    if: github.repository == 'carpentries/styles'
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        lesson: [carpentries/lesson-example]
        os: [ubuntu-20.04]
        experimental: [false]
        include:
          - os: ubuntu-20.04
            os-name: Linux
          - lesson: carpentries/lesson-example
            lesson-name: (CP) Lesson Example
            experimental: false
            os: ubuntu-20.04
            os-name: Linux
    defaults:
      run:
        shell: bash  # forces 'Git for Windows' on Windows
    env:
      RSPM: 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest'
      GITLAB_ACTIONS: false
      GITLAB_CI: true
      CI_PROJECT_NAME: lesson-example
      CI_DEFAULT_BRANCH: gh-pages
      CI_REPOSITORY_URL: "https://github.com/${{ matrix.lesson }}"
      CI_PAGES_URL: https://pages.github.com
      CI_PROJECT_TITLE: "${{ matrix.lesson-name }}"
      CI_MERGE_REQUEST_SOURCE_BRANCH_NAME: "patch-1"
    steps:
      - name: Checkout the ${{ matrix.lesson }} lesson
        uses: actions/checkout@master
        with:
          repository: ${{ matrix.lesson }}
          path: lesson
          fetch-depth: 0

      - name: Sync lesson with carpentries/styles
        working-directory: lesson
        run: |
          echo "::group::Fetch Styles"
          if [[ -n "${{ github.event.pull_request.number }}" ]]
          then
            ref="refs/pull/${{ github.event.pull_request.number }}/head"
          else
            ref="gh-pages"
          fi

          git config --global user.email "team@carpentries.org"
          git config --global user.name "The Carpentries Bot"

          git remote add styles https://github.com/carpentries/styles.git
          git fetch styles $ref:styles-ref
          echo "::endgroup::"
          echo "::group::Synchronize Styles"
          # Sync up only if necessary
          if [[ $(git rev-list --count HEAD..styles-ref) != 0 ]]
          then

            # The merge command below might fail for lessons that use remote theme
            # https://github.com/carpentries/carpentries-theme
            echo "Testing merge using recursive strategy, accepting upstream changes without committing"
            if ! git merge -s recursive -Xtheirs --no-commit styles-ref
            then

              # Remove "deleted by us, unmerged" files from the staging area.
              # these are the files that were removed from the lesson
              # but are still present in the carpentries/styles repo
              echo "Removing previously deleted files"
              git rm $(git diff --name-only --diff-filter=DU)

              # If there are still "unmerged" files,
              # let's raise an error and look into this more closely
              if [[ -n $(git diff --name-only --diff-filter=U) ]]
              then
                echo "There were unmerged files in ${{ matrix.lesson-name }}:"
                echo "$(git diff --compact-summary --diff-filter=U)"
                exit 1
              fi
            fi

            echo "Committing changes"
            git commit -m "Sync lesson with carpentries/styles"
          fi
          echo "::endgroup::"

      - name: Download gitlab-runner
        run: |
          wget -O gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
          chmod +x gitlab-runner

      - name: Build carpentries example lesson using gitlab-runner
        run: ./gitlab-runner exec docker pages --docker-volumes "$(pwd)/_site:/public" --post-build-script "rm -rf /public/* && cp -R public/* /public && chown -R $(id -u):$(id -g) /public"
